### PR TITLE
Add custom app folder in Zephyr

### PR DESCRIPTION
**Pull request by pablogs9**
This PR enables using external applications in Zephyr by using `UROS_CUSTOM_APP_FOLDER`

### CODE REVIEW

**Comment by CLansdaleBEC** [comment]
I am having some trouble getting this to work with a custom app. The files in firmware/mcu_ws/install aren't generating, I think I'm missing a step somewhere.

Steps taken: 
1. Make uros_app directory with the same format as zephyr_apps, place this at the top level workspace. Copy int32_publisher in and rename to 'custom_app'.
2. Copy microros_extensions to the uros_app folder
3. Clone micro_ros_setup in the src folder, colcon build, source setup.bash

The workspace now looks like this
Screenshot from 2020-08-31 17-56-55

4. Create: `ros2 run micro_ros_setup create_firmware_ws.sh zephyr `nucleo_h743zi`
5. Export the full path to the custom app folder UROS_CUSTOM_APP_FOLDER manually
6. Configure `ros2 run micro_ros_setup configure_firmware.sh custom_app -t serial -d 3`

So far so good, now the issue comes up during the build step.

I get an error while compiling.
```
10: fatal error: rcl/rcl.h: No such file or directory
    4 | #include <rcl/rcl.h>
      |          ^~~~~~~~~~~
```

My understanding is the app CMakeLists.txt generates and places these include files in the firmware/mcu_ws/install/include folder.
When I build without modifying CMakeLists.txt:
```
file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../mcu_ws/install)    # Default path
file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../mcu_ws/install/include)

set(MICROROS_LIB_DIR     ${CMAKE_CURRENT_SOURCE_DIR}/../../../mcu_ws/install)
set(MICROROS_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../mcu_ws/install/include)
```
These files are generated properly, but just in the wrong place (the top level workspace). This makes sense because the CMAKE_CURRENT_SOURCE_DIR has moved.

Now the weird part is when I change those files to the correct path
```
file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/mcu_ws/install)
file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/mcu_ws/install/include)

set(MICROROS_LIB_DIR     ${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/mcu_ws/install)
set(MICROROS_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/mcu_ws/install/include)
```
The install and include folders are now in the right place, but they are empty. 

It seems like a path is not set somewhere, but I couldn't find any other mention of the mcu_ws/install folder anywhere else in the project so I'm not sure where else to look. Any ideas here?

**Comment by pablogs9** [comment]
Hello @CLansdaleBEC, let me show you my approach. I think that is simpler:

I also have included a CMake variable in the last commit.

```bash
ros2 run micro_ros_setup create_firmware_ws.sh zephyr discovery_l475_iot1
mkdir my_external_apps
touch my_external_apps/COLCON_IGNORE

#For the sake of example we copy some app
cp -r firmware/zephyr_apps/apps/int32_publisher/ my_external_apps/

export UROS_CUSTOM_APP_FOLDER=$(pwd)/my_external_apps

#This should list apps inside your my_external_app folder
ros2 run micro_ros_setup configure_firmware.sh


ros2 run micro_ros_setup configure_firmware.sh int32_publisher -t serial-usb
ros2 run micro_ros_setup build_firmware.sh
```

Please notice that I have modified the `CMakeLists.txt` inside the copied app to use this new `MICRO_ROS_FIRMWARE_DIR`:

```cmake
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.13.1)

set(COMPATIBLE_BOARDS disco_l475_iot1 olimex_stm32_e407 native_posix nucleo_h743zi)

if(NOT ${BOARD} IN_LIST COMPATIBLE_BOARDS)
    message(FATAL_ERROR "App $ENV{UROS_APP} not compatible with board ${BOARD}")
endif()

include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
project(microrosapp C CXX)

FILE(GLOB app_sources src/*.c ${MICRO_ROS_FIRMWARE_DIR}/zephyr_apps/microros_extensions/libatomic.c)

target_sources(app PRIVATE ${app_sources})

zephyr_get_include_directories_for_lang_as_string(       C includes)
zephyr_get_system_include_directories_for_lang_as_string(C system_includes)
zephyr_get_compile_definitions_for_lang_as_string(       C definitions)
zephyr_get_compile_options_for_lang_as_string(           C options)

zephyr_get_include_directories_for_lang_as_string(       CXX includes_cxx)
zephyr_get_system_include_directories_for_lang_as_string(CXX system_includes_cxx)
zephyr_get_compile_definitions_for_lang_as_string(       CXX definitions_cxx)
zephyr_get_compile_options_for_lang_as_string(           CXX options_cxx)

set(external_project_cflags
    "${includes} ${definitions} ${options} ${system_includes}"
    )

set(external_project_cxxflags
    "${includes_cxx} ${definitions_cxx} ${options_cxx} ${system_includes_cxx}" 
    )

include(ExternalProject)

set(microros_src_dir   ${MICRO_ROS_FIRMWARE_DIR}/zephyr_apps/microros_extensions)
set(microros_build_dir ${CMAKE_CURRENT_BINARY_DIR}/microros_extensions)

if(CMAKE_GENERATOR STREQUAL "Unix Makefiles")
set(submake "$(MAKE)")
else()
set(submake "make")
endif()

ExternalProject_Add(
    microroslib_project                 # Name for custom target
    PREFIX     ${microros_build_dir}    # Root dir for entire project
    SOURCE_DIR ${microros_src_dir}
    BINARY_DIR ${microros_src_dir}      # This particular build system is invoked from the root
    CONFIGURE_COMMAND ""                # Skip configuring the project, e.g. with autoconf
    BUILD_COMMAND
        ${submake}
            PREFIX=${microros_src_dir}
            CC=${CMAKE_C_COMPILER}
            AR=${CMAKE_AR}
            CFLAGS=${external_project_cflags}
            CXX=${CMAKE_CXX_COMPILER}
            CXXFLAGS=${external_project_cxxflags}
            APP_META=$ENV{UROS_APP_FOLDER}/app-colcon.meta

    INSTALL_COMMAND ""      # This particular build system has no install command
    BUILD_BYPRODUCTS ${MICROROS_LIB_DIR}/libmicroros.a
    )

file(MAKE_DIRECTORY ${MICRO_ROS_FIRMWARE_DIR}/mcu_ws/install)
file(MAKE_DIRECTORY ${MICRO_ROS_FIRMWARE_DIR}/mcu_ws/install/include)

set(MICROROS_LIB_DIR     ${MICRO_ROS_FIRMWARE_DIR}/mcu_ws/install)
set(MICROROS_INCLUDE_DIR ${MICRO_ROS_FIRMWARE_DIR}/mcu_ws/install/include)

add_library(microroslib STATIC IMPORTED GLOBAL)
add_dependencies(
    microroslib
    microroslib_project
    )

add_dependencies(microroslib_project offsets_h)

set_target_properties(microroslib PROPERTIES IMPORTED_LOCATION             ${MICROROS_LIB_DIR}/libmicroros.a)
set_target_properties(microroslib PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${MICROROS_INCLUDE_DIR})

target_link_libraries(app PUBLIC microroslib)
```

Please let me know if this works for you and if it fills your requirements.
Thanks!!

**Comment by CLansdaleBEC** [comment]
That worked! Thanks a bunch

Only difference was I needed to specify UROS_CUSTOM_APP_FOLDER=$(pwd)/uros_apps/**apps**

**Comment by pablogs9** [comment]
We thought that is interesting to have this "external app folder" with a group of external applications, so `UROS_CUSTOM_APP_FOLDER` is expected to have the actual app folder inside.

Regarding the `UROS_CUSTOM_EXT_FOLDER`idea, did you have time to check it @MS71?

Thanks!

**Review by jamoralp — APPROVED** [review]
LGTM

**Pull request merged**
