### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by pablogs9** [comment]
To review micro-ROS rolling for host

**Comment by pablogs9** [comment]
Mbed failing bc [here](https://github.com/micro-ROS/micro_ros_mbed/blob/b46bfa5e5fd53b6295e557ddfad58c5863aef73f/CMakeLists.txt#L50) we do not have ` rosidl_runtime_c rosidl_typesupport_interface rosidl_typesupport_introspection_c`

**Comment by Acuadros95** [comment]
It looks like `ros:rolling` and `ubuntu:latest` are not updated to `ubuntu:jammy` distro:
```
username@mydevice:~$ docker run -it --rm --privileged ros:rolling
root@2ed4a217a21b:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

`DISTRIB_CODENAME=focal` should be `jammy`, as `rosdep` rolling repos are updated to `jammy`: [link](https://raw.githubusercontent.com/ros/rosdistro/master/rolling/distribution.yaml)
```
username@mydevice:~$ docker run -it --rm --privileged ubuntu:jammy
root@6a306e5e3960:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu Jammy Jellyfish (development branch)"
```

This PR sets the OS explicitly as a work arround to find dependencies correctly

**Comment by pablogs9** [comment]
@mergify backport galactic foxy

**Pull request merged**
