### PR TITLE
Fix logic for generic platform

### PR DESCRIPTION
**Pull request by k7g03z**
This PR fixes the incorrect logic in checking if the generic platform is being used.

https://github.com/micro-ROS/micro_ros_setup/issues/550 

Signed-off-by: Kevin Goez <kevin.goez@apex.ai>

### CODE REVIEW

**Comment by pablogs9** [comment]
Please check the CI

**Comment by Acuadros95** [comment]
That check is a little bit misleading.

As you can see here, if `$PLATFORM == generic` is true, the sourced file is exactly the same:

```bash
if [ $PLATFORM == "generic" ] && [ -d "$PREFIX/config/$RTOS/generic" ]; then
    . $PREFIX/config/$RTOS/generic/build.sh
else
    . $PREFIX/config/$RTOS/$PLATFORM/build.sh
fi
```

If you take a look at each `RTOS` folder, if the generic folder is present it should always be used. So we can just take that check out and use:

```bash
if [ -d "$PREFIX/config/$RTOS/generic" ]; then
    . $PREFIX/config/$RTOS/generic/build.sh
else
    . $PREFIX/config/$RTOS/$PLATFORM/build.sh
fi
```

**Comment by k7g03z** [comment]
> 
> If you take a look at each `RTOS` folder, if the generic folder is present it should always be used. So we can just take that check out and use:
> 
> ```shell
> if [ -d "$PREFIX/config/$RTOS/generic" ]; then
>     . $PREFIX/config/$RTOS/generic/build.sh
> else
>     . $PREFIX/config/$RTOS/$PLATFORM/build.sh
> fi
> ```

@Acuadros95 
Why would you always use the generic if the use selects a specific platform?

**Comment by Acuadros95** [comment]
@k7g03z This repo gathers different RTOSes and boards with different configuration systems.

For example, `freertos` uses a folder for each supported platform, as the configuration, flash or build process are different for each board: [detail](https://github.com/micro-ROS/micro_ros_setup/tree/humble/config/freertos).

But for `zephyr`, the different platforms are handle on the same `generic` folder: [detail](https://github.com/micro-ROS/micro_ros_setup/tree/humble/config/zephyr).

I understand its confusing, but this repository is being replaced by the [Standalone build system tools](https://github.com/micro-ROS/micro_ros_setup#standalone-build-system-tools) and we will avoid going on deep changes for now.

**Comment by k7g03z** [comment]
> @k7g03z This repo gathers different RTOSes and boards with different configuration systems.
> 
> For example, `freertos` uses a folder for each supported platform, as the configuration, flash or build process are different for each board: [detail](https://github.com/micro-ROS/micro_ros_setup/tree/humble/config/freertos).
> 
> But for `zephyr`, the different platforms are handle on the same `generic` folder: [detail](https://github.com/micro-ROS/micro_ros_setup/tree/humble/config/zephyr).
> 
> I understand its confusing, but this repository is being replaced by the [Standalone build system tools](https://github.com/micro-ROS/micro_ros_setup#standalone-build-system-tools) and we will avoid going on deep changes for now.

Based on your feedback, the check `$PLATFORM != generic` seems to be unnecessary in general as well as confusing. I've taken it out in the latest push.

**Review by Acuadros95 — APPROVED** [review]

**Comment by Acuadros95** [comment]
@mergify backport humble galactic foxy

**Pull request merged**
