### PR TITLE
Remove non-header files from include folder

### PR DESCRIPTION
**Pull request by meetgandhi-dev**
The `include` directory previously contained all files copied over, but only `*.h` and `*.hpp` files are required. This commit removes all files that do not have a `.h` or `.hpp` extension, as well as any empty directories that may result from this cleanup.

### CODE REVIEW

**Comment by meetgandhi-dev** [comment]
@pablogs9 any updates on this?

**Comment by pablogs9** [comment]
Reopening to have CI passing

**Comment by pablogs9** [comment]
@mergify backport rolling jazzy

**Comment by pablogs9** [comment]
@meetgandhi-dev thanks for the contrib!

**Pull request merged**
